# Generated by Django 5.2 on 2025-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.IntegerField(),
        ),
    ]
