# Generated by Django 5.2 on 2025-04-26 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_system', '0002_alter_book_isbn_alter_book_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='ISBN must be exactly 13 digits.', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
