# Generated by Django 5.2 on 2025-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_system', '0003_alter_book_isbn_alter_book_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('librarian', 'Librarian')], default='user', max_length=20)),
            ],
        ),
    ]
