# Generated by Django 5.2 on 2025-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_system', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('librarian', 'Librarian')], default='user', max_length=20),
        ),
    ]
